- type: rank
  id: RatRankLevymanHead
  name: Легат
  prefix: Легат
  paygrade: E5

- type: rank
  id: RatRankLevymanLead
  name: Центурион
  prefix: Центурион
  paygrade: E4

- type: rank
  id: RatRankLevymanSenior
  name: Трибун
  prefix: Трибун
  paygrade: E3

- type: rank
  id: RatRankLevymanMiddle
  name: Проктор
  prefix: Проктор
  paygrade: E2

- type: rank
  id: RatRankLevymanJunior
  name: Леви
  prefix: Леви
  paygrade: E1